[
  {
    "class": "django.core.exceptions.ValidationError",
    "message": "['The URL \"/new/url/\" does not exist']",
    "stack": [
      "src/oscar/core/validators.py:31",
      "src/oscar/core/validators.py:49",
      "src/oscar/apps/dashboard/pages/forms.py:40"
    ]
  },
  {
    "class": "django.core.exceptions.ValidationError",
    "message": "['The URL \"/new/url/\" does not exist']",
    "stack": [
      "src/oscar/core/validators.py:49",
      "src/oscar/apps/dashboard/pages/forms.py:40"
    ]
  }
]