[
  {
    "class": "django.core.exceptions.ValidationError",
    "message": "{'__all__': ['This address is already in your address book']}",
    "stack": [
      "src/oscar/apps/address/abstract_models.py:611"
    ]
  }
]