[
  {
    "class": "django.core.exceptions.ValidationError",
    "message": "['A user with this email address already exists']",
    "stack": [
      "src/oscar/apps/customer/forms.py:261"
    ]
  }
]