[
  {
    "class": "django.core.exceptions.ValidationError",
    "message": "['You cannot vote on your own reviews']",
    "stack": [
      "src/oscar/apps/catalogue/reviews/abstract_models.py:218",
      "src/oscar/apps/catalogue/reviews/abstract_models.py:172",
      "src/oscar/templatetags/display_tags.py:46"
    ]
  }
]