[
  {
    "class": "django.core.exceptions.ValidationError",
    "message": "['Must be a datetime']",
    "stack": [
      "src/oscar/apps/catalogue/abstract_models.py:1046"
    ]
  },
  {
    "class": "django.core.exceptions.ValidationError",
    "message": "['Must be a datetime']",
    "stack": [
      "src/oscar/apps/catalogue/abstract_models.py:1074",
      "src/oscar/apps/catalogue/abstract_models.py:1046"
    ]
  }
]