[
  {
    "class": "django.core.exceptions.ValidationError",
    "message": "['You cannot vote on your own reviews']",
    "stack": [
      "src/oscar/apps/catalogue/reviews/abstract_models.py:218"
    ]
  }
]