[
  {
    "class": "django.core.exceptions.ValidationError",
    "message": "['The URL \"/invalid/\" does not exist']",
    "stack": [
      "src/oscar/core/validators.py:31",
      "src/oscar/core/validators.py:49"
    ]
  },
  {
    "class": "django.core.exceptions.ValidationError",
    "message": "['The URL \"/invalid/\" does not exist']",
    "stack": [
      "src/oscar/core/validators.py:49"
    ]
  }
]